# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Sphinx to GitHub Pages'
description: 'GitHub Action to deploy Sphinx documentation to GitHub Pages'
author: 'Shengyu Zhang'
branding:
  color: 'green'
  icon: 'upload-cloud'
inputs:
  documentation_path:
    description: 'Path to Sphinx source files'
    required: false
    default: './docs'
  requirements_path:
    description: 'Path to requirements file, used in `pip install -r XXX` command'
    required: false
    default: './docs/requirements.txt'
  pyproject_extras:
    description: 'Extras of Requirement Specifier, used in `pip install .[XXX]` command'
    required: false
    default: 'docs'
  python_version:
    description: 'Version of Python'
    required: false
    default: '3.10'
  sphinx_version:
    description: 'Version of Sphinx'
    required: false
    default: ''
  cache:
    description: 'Enable cache to speed up documentation building'
    required: false
    default: false
  SSK_KEY:
    description: 'Passed to actions/checkout to enable private repos"
    required: false
    default: ''
outputs:
  page_url:
    description: 'URL to deployed GitHub Pages'
    value: ${{ steps.deployment.outputs.page_url }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      if: ${{ inputs.cache == 'true' }}
      with:
        fetch-depth: 0 # Required by git-restore-mtime
        SSH_KEY: ${{ inputs.SSH_KEY }}
    - name: Checkout
      uses: actions/checkout@v3
      if: ${{ inputs.cache == 'false' }}
      with:
        SSH_KEY: ${{ inputs.SSH_KEY }}
    - name: Setup python
      uses: actions/setup-python@v4
      if: ${{ inputs.cache == 'true' }}
      with:
        python-version: ${{ inputs.python_version }}
        cache: 'pip'
    - name: Setup python
      uses: actions/setup-python@v4
      if: ${{ inputs.cache == 'false' }}
      with:
        python-version: ${{ inputs.python_version }}

    - name: Restore cache
      uses: actions/cache@v3
      if: ${{ inputs.cache == 'true' }}
      with:
        path: /tmp/sphinxnotes-pages
        # https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache
        key: sphinxnotes-pages-${{ runner.os }}-${{ github.run_id }}
        restore-keys: |
          sphinxnotes-pages-${{ runner.os }}

    - name: Build documentation
      run: ${{ github.action_path }}/main.sh
      shell: bash
      env:
        # See https://github.com/actions/runner/issues/665
        INPUT_DOCUMENTATION_PATH: ${{ inputs.documentation_path }}
        INPUT_REQUIREMENTS_PATH: ${{ inputs.requirements_path }}
        INPUT_PYPROJECT_EXTRAS: ${{ inputs.pyproject_extras }}
        INPUT_SPHINX_VERSION: ${{ inputs.sphinx_version }}
        INPUT_CACHE: ${{ inputs.cache }}

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: /tmp/sphinxnotes-pages

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
